name: Updater (WIP)

on:
  schedule:
    - cron: 0 0 * * 0
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Provide permission to clone the repo and deploy it to GitHub Pages
permissions:
  contents: write

jobs:
  update:
    if: github.repository_owner == 'wowchemy'
    runs-on: ubuntu-latest
    steps:
      - uses: wowchemy/gh-action-updater@v1
        with:
          feed-url: https://wowchemy.com/blog/index.xml
          readme-section: news
          branch: main
